repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # prettier formats files for the web - hmtml, js, css, xml...
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
  # Black formats python3 files without changing the AST
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ["--skip-string-normalization"]

  # isort sorts Python imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  # pyugrade upgrades old python syntax
  - repo: https://github.com/asottile/pyupgrade
    # PyUpgrade dreopped support for Python3.6 after this version
    rev: v3.3.0
    hooks:
      - id: pyupgrade
